# Numpy playground
## Testing environment

In [2]:
import numpy as np

print("hello world!")
print(np.__version__)

hello world!
2.3.2


## Create arrays
- Basic structure is ndarray

In [34]:
a = np.array([1, 2, 3, 4, 5])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [35]:
b = np.array([[1,2,3],
             [3,4,5]])
print(type(b))
b

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [3, 4, 5]])

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
np.full(5, 7)

array([7, 7, 7, 7, 7])

In [39]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [40]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [41]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Dimesion, shape and size
- ndim
- shape
- size
- dtype 

In [42]:
a = np.array([1, 2, 3, 4, 5])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size:", a.size)
print("dtype:", a.dtype)

ndim: 1
shape: (5,)
size: 5
dtype: int64


In [43]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("ndim:", b.ndim)
print("shape:", b.shape)
print("size:", b.size)
print("dtype:", b.dtype)

ndim: 2
shape: (2, 3)
size: 6
dtype: int64


## Indexing

In [44]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
a[2, 1]

np.int64(80)

## Slicing

In [45]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


In [46]:
a[:, 0]

array([10, 40, 70])

In [47]:
a[:2, :2]

array([[10, 20],
       [40, 50]])

In [48]:
a[1:, 1:]

array([[50, 60],
       [80, 90]])

## Modify items

In [49]:
a = np.array([
    [1, 2],
    [3, 4]
])
a[0, 1] = 99
a

array([[ 1, 99],
       [ 3,  4]])

## Math ops

In [50]:
a = np.array([1, 2, 3, 4, 5])

In [51]:
a + 10

array([11, 12, 13, 14, 15])

In [52]:
a * 2

array([ 2,  4,  6,  8, 10])

In [53]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [54]:
a + a

array([ 2,  4,  6,  8, 10])

In [55]:
a * a

array([ 1,  4,  9, 16, 25])

In [56]:
a > 10

array([False, False, False, False, False])

## Boolean masking

In [57]:
a = np.array([1, 5, 10, 15, 20])
mask = a > 10
mask

array([False, False, False,  True,  True])

In [58]:
a[mask]

array([15, 20])

In [ ]:
a[a > 10]

In [60]:
a[(a > 5) & (a < 20)]

array([10, 15])

## Aggregates
- sum
- mean
- min
- max
- std
- median

In [63]:
a = np.array([10, 20, 30, 40, 50])
print("Sum", np.sum(a))
print("Mean", np.mean(a))
print("Min", np.min(a))
print("Max", np.max(a))
print("Median", np.median(a))
print("Std", np.std(a))

Sum 150
Mean 30.0
Min 10
Max 50
Median 30.0
Std 14.142135623730951


In [64]:
a.sum()

np.int64(150)

## Axis

In [4]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Sum axis 0", a.sum(axis=0))
print("Sum axis 1", a.sum(axis=1))

Sum axis 0 [12 15 18]
Sum axis 1 [ 6 15 24]


## Broadcasting

In [7]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([10, 20, 30])
a + b

array([[11, 22, 33],
       [14, 25, 36]])

## Reshape

In [10]:
a = np.arange(12)
print(a)
print(a.reshape(3, 4))
print(a.reshape(2, -1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Flatten vs Ravel

In [11]:
a = np.array([
    [1, 2],
    [3, 4]
])
print(a.flatten())
print(a.ravel())

[1 2 3 4]
[1 2 3 4]


## Concatenate

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

In [14]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])
np.concatenate([a, b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Random

In [16]:
rng = np.random.default_rng()

print(rng.random(5))
print(rng.integers(1, 100, size=10))
print(rng.integers(1, 100, size=(3, 4)))
print(rng.normal(0, 1, size=10))

[0.0682317  0.66904849 0.65220595 0.56909151 0.99085655]
[65 92 88 80 81 77 85  2 46 35]
[[15 47 83 45]
 [69 20  5 55]
 [92 85 41 61]]
[-0.1557229   1.80935803 -0.87699532  1.019122   -0.91340457  0.27633234
  1.58847496  0.35610107 -0.59634904 -0.34701027]


## Maths

In [17]:
a = np.array([1, 4, 9, 16, 25])
print( np.sqrt(a) )
print( np.log(a) )
print( np.exp(a) )
print( np.sin(a) )


[1. 2. 3. 4. 5.]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


## Copies and References

In [18]:
a = np.array([1, 2, 3])

b = a.copy()

b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


## dtype

In [19]:
a = np.array([1, 2, 3], dtype=np.float64)
a.dtype

dtype('float64')

## Exercise 1

Tenemos las siguientes temperaturas en Celsius:

[12, 18, 21, 25, 30, 35, 40]

Utilizando NumPy:

1. Crear un ndarray.
2. Convertir las temperaturas a Fahrenheit.
3. Encontrar la temperatura máxima.
4. Encontrar la temperatura mínima.
5. Calcular el promedio.
6. Seleccionar las temperaturas mayores a 25°C.
7. Seleccionar las temperaturas entre 20°C y 35°C.
8. Ordenar las temperaturas.
9. Convertir el array en un shape de 1 × 7.
10. Convertirlo nuevamente en un array de 7 × 1.

In [13]:
import numpy as np

temps = [12, 18, 21, 25, 30, 35, 40]
n_temps = np.array(temps)
print(n_temps)
print(type(n_temps))

n_tempsf = n_temps * (9/5) + 32
print(n_tempsf)

print(n_temps.max())
print(n_temps.min())
print(n_temps.mean())

print(n_temps[n_temps > 25])
print(n_temps[(n_temps > 20) & (n_temps < 35)])

print(np.sort(n_temps))

print(n_temps.reshape(1, 7))

print(n_temps.reshape(7, 1))

print(n_temps.reshape(7))

[12 18 21 25 30 35 40]
<class 'numpy.ndarray'>
[ 53.6  64.4  69.8  77.   86.   95.  104. ]
40
12
25.857142857142858
[30 35 40]
[21 25 30]
[12 18 21 25 30 35 40]
[[12 18 21 25 30 35 40]]
[[12]
 [18]
 [21]
 [25]
 [30]
 [35]
 [40]]
[12 18 21 25 30 35 40]


## Excercise 2

Tenemos las ventas de una empresa:

           Enero Febrero Marzo
Producto A   10    20     30
Producto B   15    25     35
Producto C    5    15     25

Crear el array y calcular:

1. Ventas totales.
2. Ventas por producto.
3. Ventas por mes.
4. Producto con mayores ventas.
5. Mes con mayores ventas.
6. Todas las ventas mayores a 20.
7. Promedio de ventas.

In [32]:
import string
import numpy as np

letters = string.ascii_uppercase
months = [
    "January", "February", "March", "April",
    "May", "June", "July", "August",
    "September", "October", "November", "December"
]
sales = [[10, 20, 30],
         [15, 25, 35],
         [ 5, 15, 25]]

n_sales = np.array(sales)
print(n_sales)

print("Ventas totales", np.sum(n_sales))
max_per_product = np.sum(n_sales, axis=1)
print("Ventas por producto", max_per_product)
max_per_month = np.sum(n_sales, axis=0)
print("Ventas por mes", np.sum(n_sales, axis=0))

max_product_sales = np.max(max_per_product)
max_product = np.argmax(max_per_product)
max_product_ref = letters[max_product]
print("Producto con mayores ventas", max_product_sales)
print("Producto con mayores ventas", max_product)
print("Producto con mayores ventas", max_product_ref)

max_month_sales = np.max(max_per_month)
max_month = np.argmax(max_per_month)
max_month_ref = months[max_month]
print("Mes con mayores ventas", max_month_sales)
print("Mes con mayores ventas", max_month)
print("Mes con mayores ventas", max_month_ref)

i_gt_20 = np.where(n_sales > 20)
print("Ventas mayores a 20", n_sales[i_gt_20])

print("Promedio de todas las ventas", np.mean(n_sales))

[[10 20 30]
 [15 25 35]
 [ 5 15 25]]
Ventas totales 180
Ventas por producto [60 75 45]
Ventas por mes [30 60 90]
Producto con mayores ventas 75
Producto con mayores ventas 1
Producto con mayores ventas B
Mes con mayores ventas 90
Mes con mayores ventas 2
Mes con mayores ventas March
Ventas mayores a 20 [30 25 35 25]
Promedio de todas las ventas 20.0
